szakdolgozat_ules_ules_index:
    pattern:    /
    defaults:   { _controller: "SzakdolgozatUlesBundle:Ules:index" }

szakdolgozat_ules_ules_new:
    pattern:    /uj
    defaults:   { _controller: "SzakdolgozatUlesBundle:Ules:new" }

szakdolgozat_ules_ules_edit:
    pattern:    /{id}/szerkesztes
    defaults:   { _controller: "SzakdolgozatUlesBundle:Ules:edit" }

szakdolgozat_ules_ules_delete:
    pattern:    /{id}/torles
    defaults:   { _controller: "SzakdolgozatUlesBundle:Ules:delete" }
    requirements:
        _method: POST

szakdolgozat_ules_dokumentum_new:
    pattern:    /{id}/uj_dokumentum
    defaults:   { _controller: "SzakdolgozatUlesBundle:Dokumentum:new" }
    requirements:
        _method: POST

szakdolgozat_ules_dokumentum_download:
    pattern:    /dokumentum_letoltes/{dokumentum_id}
    defaults:   { _controller: "SzakdolgozatUlesBundle:Dokumentum:download" }
