services:
    szakdolgozat.ules.ules_param_converter:
        class: Szakdolgozat\UlesBundle\Request\ParamConverter\UlesParamConverter
        arguments: [@doctrine.orm.default_entity_manager]
        tags:
            - { name: "request.param_converter", priority: 100 }

    szakdolgozat.ules.dokumentum_param_converter:
        class: Szakdolgozat\UlesBundle\Request\ParamConverter\DokumentumParamConverter
        arguments: [@doctrine.orm.default_entity_manager]
        tags:
            - { name: "request.param_converter", priority: 100 }
