services:
    szakdolgozat.ules.ules_param_converter:
        class: Szakdolgozat\UlesBundle\Request\ParamConverter\UlesParamConverter
        arguments: [@doctrine.orm.default_entity_manager]
        tags:
            - { name: "request.param_converter", priority: 100 }

    szakdolgozat.ules.dokumentum_param_converter:
        class: Szakdolgozat\UlesBundle\Request\ParamConverter\DokumentumParamConverter
        arguments: [@doctrine.orm.default_entity_manager]
        tags:
            - { name: "request.param_converter", priority: 100 }

    szakdolgozat.ules.gcal_event_listener:
        class: Szakdolgozat\UlesBundle\EventListener\GcalEventListener
        arguments: [@session, "%gcal_client_id%", "%gcal_client_secret%", "%gcal_refresh_token%"]
        tags:
            - { name: "kernel.event_subscriber" }
