szakdolgozat_jegyzokonyv_jegyzokonyv_index:
    pattern:  /
    defaults: { _controller: SzakdolgozatJegyzokonyvBundle:Jegyzokonyv:index }

szakdolgozat_jegyzokonyv_jegyzokonyv_new:
    pattern:    /uj
    defaults:   { _controller: SzakdolgozatJegyzokonyvBundle:Jegyzokonyv:new }
