szakdolgozat_jegyzokonyv_jegyzokonyv_index:
    pattern:  /
    defaults: { _controller: SzakdolgozatJegyzokonyvBundle:Jegyzokonyv:index }

szakdolgozat_jegyzokonyv_jegyzokonyv_new:
    pattern:    /uj
    defaults:   { _controller: SzakdolgozatJegyzokonyvBundle:Jegyzokonyv:newGet }
    requirements:
        _method: GET

szakdolgozat_jegyzokonyv_jegyzokonyv_new_post:
    pattern:    /uj
    defaults:   { _controller: SzakdolgozatJegyzokonyvBundle:Jegyzokonyv:newPost }
    requirements:
        _method: POST

szakdolgozat_jegyzokonyv_jegyzokonyv_edit:
    pattern:    /{id}/szerkesztes
    defaults:   { _controller: SzakdolgozatJegyzokonyvBundle:Jegyzokonyv:edit }

szakdolgozat_jegyzokonyv_jegyzokonyv_show:
    pattern:    /{id}/megtekintes
    defaults:   { _controller: SzakdolgozatJegyzokonyvBundle:Jegyzokonyv:show }

szakdolgozat_jegyzokonyv_jegyzokonyv_pdf:
    pattern:    /{id}/pdf
    defaults:   { _controller: SzakdolgozatJegyzokonyvBundle:Jegyzokonyv:pdf }

szakdolgozat_jegyzokonyv_jegyzokonyv_lezarasifolyamat:
    pattern:    /{id}/lezarasifolyamat
    defaults:   { _controller: SzakdolgozatJegyzokonyvBundle:Jegyzokonyv:lezarasifolyamat }
    requirements:
        _method: POST
