szakdolgozat_jegyzokonyv_jegyzokonyv_index:
    pattern:  /
    defaults: { _controller: SzakdolgozatJegyzokonyvBundle:Jegyzokonyv:index }

szakdolgozat_jegyzokonyv_jegyzokonyv_new:
    pattern:    /uj
    defaults:   { _controller: SzakdolgozatJegyzokonyvBundle:Jegyzokonyv:newGet }
    requirements:
        _method: GET

szakdolgozat_jegyzokonyv_jegyzokonyv_new_post:
    pattern:    /uj
    defaults:   { _controller: SzakdolgozatJegyzokonyvBundle:Jegyzokonyv:newPost }
    requirements:
        _method: POST
