parameters:
#    szakdolgozat_szakdolgozat.example.class: Szakdolgozat\SzakdolgozatBundle\Example

services:
#    szakdolgozat_szakdolgozat.example:
#        class: %szakdolgozat_szakdolgozat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
