parameters:
#    szakdolgozat_jegyzokony.example.class: Szakdolgozat\JegyzokonyBundle\Example

services:
#    szakdolgozat_jegyzokony.example:
#        class: %szakdolgozat_jegyzokony.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
