szakdolgozat_jegyzokony:
    resource: "@SzakdolgozatJegyzokonyBundle/Resources/config/routing.yml"
    prefix:   /jegyzokonyv

szakdolgozat_ules:
    resource: "@SzakdolgozatUlesBundle/Resources/config/routing.yml"
    prefix:   /ules

szakdolgozat_szakdolgozat:
    resource: "@SzakdolgozatSzakdolgozatBundle/Resources/config/routing.yml"
    prefix:   /

szakdolgozat_felhasznalo:
    resource: "@SzakdolgozatFelhasznaloBundle/Resources/config/routing.yml"
    prefix: /felhasznalo

fp_openid_security:
    resource: "@FpOpenIdBundle/Resources/config/routing/security.xml"

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
