jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        openid_user_manager:
            id: szakdolgozat.felhasznalo.openid_user_manager
        database:
            entity: { class: SzakdolgozatFelhasznaloBundle:Felhasznalo, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            logout: true
            fp_openid:
                create_user_if_not_exists: true
                provider: openid_user_manager
                required_attributes:
                    - contact/email


    access_control:
        - { path: ^/login_openid$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/felhasznalo, role: ROLE_ADMINISZTRATOR }
        - { path: ^/, role: IS_AUTHENTICATED_OPENID }

        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
