szakdolgozat_felhasznalo_felhasznalo_index:
    pattern:    /
    defaults:  { _controller: SzakdolgozatFelhasznaloBundle:Felhasznalo:index }

szakdolgozat_felhasznalo_felhasznalo_new:
    pattern:    /uj
    defaults:   { _controller: SzakdolgozatFelhasznaloBundle:Felhasznalo:new }

szakdolgozat_felhasznalo_felhasznalo_edit:
    pattern:    /{id}/szerkesztes
    defaults:   { _controller: SzakdolgozatFelhasznaloBundle:Felhasznalo:edit }
