services:
    szakdolgozat.felhasznalo.openid_user_manager:
        class: Szakdolgozat\FelhasznaloBundle\Security\User\OpenIdUserManager
        arguments: [@fp_openid.identity_manager, @doctrine.orm.entity_manager]
