services:
    szakdolgozat.felhasznalo.openid_user_manager:
        class: Szakdolgozat\FelhasznaloBundleBundle\Entity\OpenIdUserManager
        arguments: [@fp_openid.identity_manager, @doctrine.orm.entity_manager]
