services:
    szakdolgozat.felhasznalo.openid_user_manager:
        class: Szakdolgozat\FelhasznaloBundle\Security\User\OpenIdUserManager
        arguments: [@fp_openid.identity_manager, @doctrine.orm.entity_manager]

    szakdolgozat.felhasznalo.felhasznalo_param_converter:
        class: Szakdolgozat\FelhasznaloBundle\Request\ParamConverter\FelhasznaloParamConverter
        arguments: [@doctrine.orm.default_entity_manager]
        tags:
            - { name: "request.param_converter", priority: 100 }

    szakdolgozat.felhasznalo.szervezeti_egyseg_param_converter:
        class: Szakdolgozat\FelhasznaloBundle\Request\ParamConverter\SzervezetiEgysegParamConverter
        arguments: [@doctrine.orm.default_entity_manager]
        tags:
            - { name: "request.param_converter", priority: 100 }
